import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { PostsProvider } from "@/context/PostContext"
import { UserProvider } from '@/context/UserContext'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <UserProvider>
          <PostsProvider>
            {children}
          </PostsProvider>
        </UserProvider>
      </body>
    </html>
  )
}
